type PermissionCode = {
  [K in
    | 'denialAllAccess'
    | 'viewDashboard'
    | 'viewUser'
    | 'viewRole'
    | 'updateRolePermission'
    | 'deleteRole'
    | 'createProject'
    | 'viewProjectHistory'
    | 'viewReport'
    | 'viewDataView'
    | 'viewProjectSummary'
    | 'viewProjectVirtualization'
    | 'viewRequest'
    | 'approveRequest'
    | 'updateUserInfo'
    | 'banUser'
    | 'deleteUser'
    | 'createUser'
    | 'updateProjectDetails'
    | 'deleteProject'
    | 'updateProjectStatus'
    | 'viewData'
    | 'filterData'
    | 'virtualizeData'
    | 'viewMap'
    | 'exportData'
    | 'exportGraph'
    | 'viewOrganizationInfo'
    | 'updateOrganizationInfo'
    | 'viewBillingInfo'
    | 'updateBillingInfo'
    | 'calibrateProject'
    | 'collectData'
    | 'requestEditData'
    | 'requestDeleteData'
    | 'cloneProject'
    | 'viewProvincesVirtualization'
    | 'viewDataBeingCollected'
    | 'viewUsersInRole'
    | 'createRole']: number;
};

export const permissionCode: PermissionCode = {
  denialAllAccess: 0,
  viewDashboard: 101,
  viewUser: 201,
  viewRole: 206,
  updateRolePermission: 207,
  deleteRole: 208,
  createProject: 304,
  viewProjectHistory: 301,
  viewReport: 507,
  viewDataView: 501,
  viewProjectSummary: 102,
  viewProjectVirtualization: 103,
  viewRequest: 104,
  approveRequest: 105,
  updateUserInfo: 202,
  banUser: 203,
  deleteUser: 204,
  createUser: 205,
  updateProjectDetails: 302,
  deleteProject: 303,
  updateProjectStatus: 305,
  viewData: 501,
  filterData: 502,
  virtualizeData: 503,
  viewMap: 504,
  exportData: 505,
  exportGraph: 506,
  viewOrganizationInfo: 601,
  updateOrganizationInfo: 602,
  viewBillingInfo: 603,
  updateBillingInfo: 604,
  calibrateProject: 106,
  collectData: 701,
  requestEditData: 702,
  requestDeleteData: 703,
  cloneProject: 306,
  viewProvincesVirtualization: 107,
  viewDataBeingCollected: 704,
  viewUsersInRole: 209,
  createRole: 209,
};
